server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shkaf
    username: admin
    password: 123qwe
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  liquibase:
    change-log: classpath:database/changelog/InitialMigration.xml
    enabled: true
    drop-first: false
    default-schema: public