spring:
  datasource:
#    url: jdbc:postgresql://localhost:5432/shkaf
#    locally
    url: jdbc:postgresql://localhost:5432/wishlist_dev
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  liquibase:
    change-log: classpath:database/changelog/InitialMigration.xml
    enabled: true
    drop-first: false
    default-schema: public
  thymeleaf:
    cache: false

# метрики доступны здесь http://localhost:8181/actuator/prometheus
# source: https://habr.com/ru/articles/548700/
management:
  endpoints:
    web:
      exposure:
#        add info, metrics
        include: health,prometheus
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true
